package pl.intertell.technik.ui.screens

import android.Manifest
import android.content.ActivityNotFoundException
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Color
import android.location.LocationManager
import android.net.Uri
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Layers
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CheckboxDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color as ComposeColor
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import androidx.lifecycle.compose.LocalLifecycleOwner
import org.maplibre.android.camera.CameraUpdateFactory
import org.maplibre.android.geometry.LatLng
import org.maplibre.android.location.LocationComponentActivationOptions
import org.maplibre.android.location.modes.CameraMode
import org.maplibre.android.location.modes.RenderMode
import org.maplibre.android.maps.MapLibreMap
import org.maplibre.android.maps.MapView
import org.maplibre.android.maps.Style
import org.maplibre.android.style.expressions.Expression
import org.maplibre.android.style.layers.CircleLayer
import org.maplibre.android.style.layers.LineLayer
import org.maplibre.android.style.layers.PropertyFactory
import org.maplibre.android.style.sources.GeoJsonSource
import pl.intertell.technik.BuildConfig
import pl.intertell.technik.TechnicianViewModel
import pl.intertell.technik.data.InfrastructureMap
import pl.intertell.technik.data.LayerStyle
import pl.intertell.technik.ui.theme.IntertellColors
import pl.intertell.technik.ui.theme.IntertellType

private const val QFIELD_PACKAGE = "ch.opengis.qfield"
private const val INFRASTRUCTURE_SOURCE_ID = "infrastructure"
private const val LINE_LAYER_ID = "infrastructure-lines"
private const val POINT_LAYER_ID = "infrastructure-points"

// Roughly the middle of Poland — a reasonable default before the technician
// pans to their own area or a GPS fix arrives; there's no server-computed
// bounding box to fit to (see server's internal/qfield).
private val POLAND_CENTER = LatLng(52.06, 19.48)
private const val POLAND_ZOOM = 6.0

// Cycled by layer name (hashed) so each GeoPackage table gets a stable,
// distinct color without the server needing to know anything about styling
// — the .qgz project's own QGIS symbology isn't parsed (see
// internal/qfield/geopackage.go's doc comment).
private val LAYER_PALETTE = listOf(
    "#0E86C4", "#D93B1E", "#2E9E5B", "#F2A93B",
    "#8B5CF6", "#EC4899", "#14B8A6", "#F97316",
)

private fun colorForLayer(name: String): Int =
    Color.parseColor(LAYER_PALETTE[(name.hashCode() and Int.MAX_VALUE) % LAYER_PALETTE.size])

private fun safeParseColor(hex: String?, fallback: Int): Int =
    if (hex.isNullOrBlank()) fallback else runCatching { Color.parseColor(hex) }.getOrDefault(fallback)

/** A representative single color for a table's layers-menu checkbox swatch. */
private fun swatchColor(table: String, styles: Map<String, LayerStyle>): Int {
    val style = styles[table]
    val hex = style?.default ?: style?.categories?.values?.firstOrNull()
    return safeParseColor(hex, colorForLayer(table))
}

// GeoPackage table names generated by QField carry a trailing UUID (e.g.
// "..._947c5a8f_c98c_46c2_9b1d_adc6ebbc6a01") that's meaningless to a
// technician — stripped for display only, the raw table name is still what
// gets toggled/matched everywhere else.
private val TABLE_UUID_SUFFIX = Regex("_[0-9a-fA-F]{8}_[0-9a-fA-F]{4}_[0-9a-fA-F]{4}_[0-9a-fA-F]{4}_[0-9a-fA-F]{12}$")

private fun displayLayerName(table: String): String =
    TABLE_UUID_SUFFIX.replace(table, "")
        .split("_")
        .filter { it.isNotBlank() }
        .joinToString(" ") { it.replaceFirstChar(Char::uppercase) }

@Composable
fun QgisScreen(viewModel: TechnicianViewModel) {
    val context = LocalContext.current
    val infrastructure by viewModel.infrastructureGeoJson.collectAsState()
    val loading by viewModel.infrastructureLoading.collectAsState()
    val error by viewModel.infrastructureError.collectAsState()
    val visibleLayers by viewModel.visibleInfrastructureLayers.collectAsState()
    val styles by viewModel.infrastructureStyles.collectAsState()

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(20.dp),
    ) {
        Text("QGIS", style = IntertellType.headline, color = IntertellColors.TextPrimary)
        Text(
            "Mapa infrastruktury sieciowej — przebiegi światłowodów, szafki i punkty dystrybucyjne.",
            style = IntertellType.body,
            color = IntertellColors.Text6,
            modifier = Modifier.padding(top = 6.dp),
        )

        Box(
            modifier = Modifier
                .fillMaxWidth()
                .weight(1f)
                .padding(top = 16.dp)
                .clip(RoundedCornerShape(18.dp))
                .background(IntertellColors.ScreenBackground),
            contentAlignment = Alignment.Center,
        ) {
            when {
                infrastructure != null -> InfrastructureMapView(
                    infrastructure = infrastructure!!,
                    visibleLayers = visibleLayers,
                    styles = styles,
                    onToggleLayer = viewModel::toggleInfrastructureLayer,
                    modifier = Modifier.fillMaxSize(),
                )
                loading -> CircularProgressIndicator(color = IntertellColors.Accent)
                error != null -> Column(modifier = Modifier.padding(24.dp)) {
                    Text(
                        "Mapa sieci jest niedostępna.",
                        style = IntertellType.bodyBold,
                        color = IntertellColors.TextPrimary,
                    )
                    Text(
                        error ?: "",
                        style = IntertellType.bodySmall,
                        color = IntertellColors.Text45,
                        modifier = Modifier.padding(top = 6.dp),
                    )
                }
                else -> CircularProgressIndicator(color = IntertellColors.Accent)
            }
        }

        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 14.dp)
                .clip(RoundedCornerShape(12.dp))
                .clickable { openQField(context) }
                .padding(vertical = 10.dp),
            horizontalArrangement = Arrangement.Center,
        ) {
            Text("Otwórz w aplikacji QField →", style = IntertellType.bodyBold, color = IntertellColors.Accent)
        }
    }
}

@Composable
private fun InfrastructureMapView(
    infrastructure: InfrastructureMap,
    visibleLayers: Set<String>,
    styles: Map<String, LayerStyle>,
    onToggleLayer: (String) -> Unit,
    modifier: Modifier = Modifier,
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val mapView = remember {
        MapView(context).apply { onCreate(null) }
    }
    var mapLibreMap by remember { mutableStateOf<MapLibreMap?>(null) }
    var showLayersMenu by remember { mutableStateOf(false) }

    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_START -> mapView.onStart()
                Lifecycle.Event.ON_RESUME -> mapView.onResume()
                Lifecycle.Event.ON_PAUSE -> mapView.onPause()
                Lifecycle.Event.ON_STOP -> mapView.onStop()
                Lifecycle.Event.ON_DESTROY -> mapView.onDestroy()
                else -> Unit
            }
        }
        lifecycleOwner.lifecycle.addObserver(observer)
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
            mapView.onDestroy()
        }
    }

    Box(modifier = modifier) {
        AndroidView(factory = { mapView }, modifier = Modifier.fillMaxSize()) { view ->
            view.getMapAsync { map ->
                mapLibreMap = map
                map.moveCamera(CameraUpdateFactory.newLatLngZoom(POLAND_CENTER, POLAND_ZOOM))
                val styleUrl = "https://api.maptiler.com/maps/streets-v2/style.json?key=${BuildConfig.MAPTILER_API_KEY}"
                map.setStyle(Style.Builder().fromUri(styleUrl)) { style ->
                    if (style.getSource(INFRASTRUCTURE_SOURCE_ID) != null) return@setStyle
                    // The file:// URI constructor silently loaded nothing on
                    // real devices (MapLibre's native file source appears not
                    // to handle it reliably) — reading the text ourselves and
                    // using the String constructor is the same approach the
                    // pre-OOM-fix code used, and is safe now that the backend
                    // trims the payload to a couple MB (see internal/qfield).
                    style.addSource(GeoJsonSource(INFRASTRUCTURE_SOURCE_ID, infrastructure.file.readText()))
                    style.addLayer(
                        LineLayer(LINE_LAYER_ID, INFRASTRUCTURE_SOURCE_ID)
                            .withProperties(
                                PropertyFactory.lineColor(layerColorExpression(infrastructure.layers, styles)),
                                PropertyFactory.lineWidth(3f),
                            ),
                    )
                    style.addLayer(
                        CircleLayer(POINT_LAYER_ID, INFRASTRUCTURE_SOURCE_ID)
                            .withProperties(
                                PropertyFactory.circleColor(layerColorExpression(infrastructure.layers, styles)),
                                PropertyFactory.circleRadius(6f),
                                PropertyFactory.circleStrokeColor(Color.WHITE),
                                PropertyFactory.circleStrokeWidth(2f),
                            ),
                    )
                    applyLayerFilters(style, infrastructure.layers, visibleLayers)

                    // Permission was already requested at app startup
                    // (MainActivity.askForLocationPermission) — this just
                    // skips the indicator if it was denied, same as
                    // elsewhere in the app.
                    if (hasLocationPermission(context)) {
                        map.locationComponent.apply {
                            activateLocationComponent(LocationComponentActivationOptions.builder(context, style).build())
                            isLocationComponentEnabled = true
                            renderMode = RenderMode.COMPASS
                            cameraMode = CameraMode.NONE
                        }
                        lastKnownLocation(context)?.let { location ->
                            map.moveCamera(CameraUpdateFactory.newLatLngZoom(LatLng(location.latitude, location.longitude), 14.0))
                        }
                    }
                }
            }
        }

        // Live filter updates when a checkbox is toggled — the source/layers
        // themselves are only ever created once (see the style.getSource
        // guard above), this just re-applies which features they show.
        LaunchedEffect(visibleLayers, mapLibreMap) {
            val style = mapLibreMap?.style ?: return@LaunchedEffect
            applyLayerFilters(style, infrastructure.layers, visibleLayers)
        }

        if (infrastructure.layers.isNotEmpty()) {
            Box(modifier = Modifier.align(Alignment.TopEnd).padding(12.dp)) {
                IconButton(
                    onClick = { showLayersMenu = !showLayersMenu },
                    modifier = Modifier
                        .size(40.dp)
                        .clip(CircleShape)
                        .background(IntertellColors.ScreenBackground),
                ) {
                    Icon(Icons.Filled.Layers, contentDescription = "Warstwy mapy", tint = IntertellColors.Accent)
                }
                if (showLayersMenu) {
                    LazyColumn(
                        modifier = Modifier
                            .padding(top = 48.dp)
                            .width(240.dp)
                            .heightIn(max = 320.dp)
                            .clip(RoundedCornerShape(14.dp))
                            .background(IntertellColors.ScreenBackground)
                            .padding(8.dp),
                    ) {
                        items(infrastructure.layers) { layer ->
                            Row(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clickable { onToggleLayer(layer) }
                                    .padding(vertical = 4.dp),
                                verticalAlignment = Alignment.CenterVertically,
                            ) {
                                Checkbox(
                                    checked = layer in visibleLayers,
                                    onCheckedChange = { onToggleLayer(layer) },
                                    colors = CheckboxDefaults.colors(checkedColor = ComposeColor(swatchColor(layer, styles))),
                                )
                                Text(displayLayerName(layer), style = IntertellType.bodySmall, color = IntertellColors.TextPrimary)
                            }
                        }
                    }
                }
            }
        }
    }
}

// Builds a per-feature color expression keyed on which GeoPackage table
// ("layer") a feature came from — and, for a table with a categorized QGIS
// renderer (e.g. cable capacity), a nested match on that table's own
// attribute so QField's actual per-category coloring is reproduced instead
// of one flat color per table.
private fun layerColorExpression(layers: List<String>, styles: Map<String, LayerStyle>): Expression {
    if (layers.isEmpty()) return Expression.color(Color.parseColor(LAYER_PALETTE[0]))
    val stops = layers.map { table -> Expression.stop(table, layerOutputExpression(table, styles)) }.toTypedArray()
    return Expression.match(Expression.get("layer"), layerOutputExpression(layers.first(), styles), *stops)
}

private fun layerOutputExpression(table: String, styles: Map<String, LayerStyle>): Expression {
    val style = styles[table]
    val fallback = colorForLayer(table)
    val field = style?.field
    if (style != null && field != null && style.categories.isNotEmpty()) {
        val catStops = style.categories.map { (value, hex) ->
            Expression.stop(value, Expression.color(safeParseColor(hex, fallback)))
        }.toTypedArray()
        return Expression.match(Expression.get(field), Expression.color(safeParseColor(style.default, fallback)), *catStops)
    }
    return Expression.color(safeParseColor(style?.default, fallback))
}

// GeoPackage exports from QGIS are almost always Multi*-typed even for
// single-part features, so a filter on bare "LineString"/"Point" alone
// silently matches nothing — that was the earlier bug that made the layer
// render invisibly despite loading correctly.
private fun applyLayerFilters(style: Style, layers: List<String>, visibleLayers: Set<String>) {
    val lineTypeFilter = Expression.any(
        Expression.eq(Expression.geometryType(), "LineString"),
        Expression.eq(Expression.geometryType(), "MultiLineString"),
    )
    val pointTypeFilter = Expression.any(
        Expression.eq(Expression.geometryType(), "Point"),
        Expression.eq(Expression.geometryType(), "MultiPoint"),
    )
    // No layer list (e.g. an older server that hasn't sent X-Qfield-Layers
    // yet) means "don't filter by layer name at all" — otherwise an empty
    // visibleLayers set would hide every feature instead of showing them
    // all, which is worse than not having the toggle menu at all.
    if (layers.isEmpty()) {
        (style.getLayer(LINE_LAYER_ID) as? LineLayer)?.setFilter(lineTypeFilter)
        (style.getLayer(POINT_LAYER_ID) as? CircleLayer)?.setFilter(pointTypeFilter)
        return
    }
    val visibleExpr = Expression.literal(visibleLayers.toTypedArray())
    (style.getLayer(LINE_LAYER_ID) as? LineLayer)?.setFilter(
        Expression.all(lineTypeFilter, Expression.`in`(Expression.get("layer"), visibleExpr)),
    )
    (style.getLayer(POINT_LAYER_ID) as? CircleLayer)?.setFilter(
        Expression.all(pointTypeFilter, Expression.`in`(Expression.get("layer"), visibleExpr)),
    )
}

private fun hasLocationPermission(context: Context): Boolean =
    ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED ||
        ContextCompat.checkSelfPermission(context, Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED

private fun lastKnownLocation(context: Context): android.location.Location? {
    val locationManager = context.getSystemService(Context.LOCATION_SERVICE) as? LocationManager ?: return null
    return try {
        locationManager.getProviders(true)
            .mapNotNull { locationManager.getLastKnownLocation(it) }
            .maxByOrNull { it.time }
    } catch (e: SecurityException) {
        null
    }
}

private fun openQField(context: Context) {
    val launchIntent = context.packageManager.getLaunchIntentForPackage(QFIELD_PACKAGE)
    if (launchIntent != null) {
        context.startActivity(launchIntent)
        return
    }
    try {
        context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id=$QFIELD_PACKAGE")))
    } catch (e: ActivityNotFoundException) {
        context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://play.google.com/store/apps/details?id=$QFIELD_PACKAGE")))
    }
}
